import portrait
import os

croma = 'test/img/XX11.jpg'
value = ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut aliquet est."
		" Sed convallis dignissim justo nec porta. Sed volutpat, purus et efficitur porta, "
		"justo dui ornare eros, eget dictum dui massa nec massa. Nunc finibus gravida euismod. "
		"Praesent quis dui pellentesque, egestas nibh sit amet, fermentum dolor. Donec viverra pretium elementum."
		" Proin fermentum velit a nibh rutrum feugiat. Aliquam vehicula lorem quis justo pretium egestas. "
		"Aliquam erat volutpat. Suspendisse vestibulum tempor dui, ac mollis dolor pellentesque et. "
		"Vestibulum pharetra vel mauris eu egestas. Sed at placerat ligula. In hac habitasse platea dictumst. "
		"Etiam semper sollicitudin velit et hendrerit. Mauris eu pharetra libero.Aliquam vel tortor nec urna semper aliquam. "
		"Etiam at ante blandit, faucibus neque at, eleifend urna. Ut urna odio, tempor non ex nec, tristique volutpat sem. "
		"Quisque libero lorem, pulvinar in faucibus non, vulputate ut elit. Phasellus scelerisque lacinia mi, ut euismod felis mollis id. "
		"Cras pulvinar massa non ultricies ullamcorper. Mauris orci tellus, malesuada sed pellentesque rhoncus, condimentum sed sem. "
		"Praesent nibh felis, sagittis mollis mi id, varius fermentum felis."
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut aliquet est."
		" Sed convallis dignissim justo nec porta. Sed volutpat, purus et efficitur porta, "
		"justo dui ornare eros, eget dictum dui massa nec massa. Nunc finibus gravida euismod. "
		"Praesent quis dui pellentesque, egestas nibh sit amet, fermentum dolor. Donec viverra pretium elementum."
		" Proin fermentum velit a nibh rutrum feugiat. Aliquam vehicula lorem quis justo pretium egestas. "
		"Aliquam erat volutpat. Suspendisse vestibulum tempor dui, ac mollis dolor pellentesque et. "
		"Vestibulum pharetra vel mauris eu egestas. Sed at placerat ligula. In hac habitasse platea dictumst. "
		"Etiam semper sollicitudin velit et hendrerit. Mauris eu pharetra libero.Aliquam vel tortor nec urna semper aliquam. "
		"Etiam at ante blandit, faucibus neque at, eleifend urna. Ut urna odio, tempor non ex nec, tristique volutpat sem. "
		"Quisque libero lorem, pulvinar in faucibus non, vulputate ut elit. Phasellus scelerisque lacinia mi, ut euismod felis mollis id. "
		"Cras pulvinar massa non ultricies ullamcorper. Mauris orci tellus, malesuada sed pellentesque rhoncus, condimentum sed sem. "
		"Praesent nibh felis, sagittis mollis mi id, varius fermentum felis."
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut aliquet est."
		" Sed convallis dignissim justo nec porta. Sed volutpat, purus et efficitur porta, "
		"justo dui ornare eros, eget dictum dui massa nec massa. Nunc finibus gravida euismod. "
		"Praesent quis dui pellentesque, egestas nibh sit amet, fermentum dolor. Donec viverra pretium elementum."
		" Proin fermentum velit a nibh rutrum feugiat. Aliquam vehicula lorem quis justo pretium egestas. "
		"Aliquam erat volutpat. Suspendisse vestibulum tempor dui, ac mollis dolor pellentesque et. "
		"Vestibulum pharetra vel mauris eu egestas. Sed at placerat ligula. In hac habitasse platea dictumst. "
		"Etiam semper sollicitudin velit et hendrerit. Mauris eu pharetra libero.Aliquam vel tortor nec urna semper aliquam. "
		"Etiam at ante blandit, faucibus neque at, eleifend urna. Ut urna odio, tempor non ex nec, tristique volutpat sem. "
		"Quisque libero lorem, pulvinar in faucibus non, vulputate ut elit. Phasellus scelerisque lacinia mi, ut euismod felis mollis id. "
		"Cras pulvinar massa non ultricies ullamcorper. Mauris orci tellus, malesuada sed pellentesque rhoncus, condimentum sed sem. "
		"Praesent nibh felis, sagittis mollis mi id, varius fermentum felis."
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut aliquet est."
		" Sed convallis dignissim justo nec porta. Sed volutpat, purus et efficitur porta, "
		"justo dui ornare eros, eget dictum dui massa nec massa. Nunc finibus gravida euismod. "
		"Praesent quis dui pellentesque, egestas nibh sit amet, fermentum dolor. Donec viverra pretium elementum."
		" Proin fermentum velit a nibh rutrum feugiat. Aliquam vehicula lorem quis justo pretium egestas. "
		"Aliquam erat volutpat. Suspendisse vestibulum tempor dui, ac mollis dolor pellentesque et. "
		"Vestibulum pharetra vel mauris eu egestas. Sed at placerat ligula. In hac habitasse platea dictumst. "
		"Etiam semper sollicitudin velit et hendrerit. Mauris eu pharetra libero.Aliquam vel tortor nec urna semper aliquam. "
		"Etiam at ante blandit, faucibus neque at, eleifend urna. Ut urna odio, tempor non ex nec, tristique volutpat sem. "
		"Quisque libero lorem, pulvinar in faucibus non, vulputate ut elit. Phasellus scelerisque lacinia mi, ut euismod felis mollis id. "
		"Cras pulvinar massa non ultricies ullamcorper. Mauris orci tellus, malesuada sed pellentesque rhoncus, condimentum sed sem. "
		"Praesent nibh felis, sagittis mollis mi id, varius fermentum felis."
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut aliquet est."
		" Sed convallis dignissim justo nec porta. Sed volutpat, purus et efficitur porta, "
		"justo dui ornare eros, eget dictum dui massa nec massa. Nunc finibus gravida euismod. "
		"Praesent quis dui pellentesque, egestas nibh sit amet, fermentum dolor. Donec viverra pretium elementum."
		" Proin fermentum velit a nibh rutrum feugiat. Aliquam vehicula lorem quis justo pretium egestas. "
		"Aliquam erat volutpat. Suspendisse vestibulum tempor dui, ac mollis dolor pellentesque et. "
		"Vestibulum pharetra vel mauris eu egestas. Sed at placerat ligula. In hac habitasse platea dictumst. "
		"Etiam semper sollicitudin velit et hendrerit. Mauris eu pharetra libero.Aliquam vel tortor nec urna semper aliquam. "
		"Etiam at ante blandit, faucibus neque at, eleifend urna. Ut urna odio, tempor non ex nec, tristique volutpat sem. "
		"Quisque libero lorem, pulvinar in faucibus non, vulputate ut elit. Phasellus scelerisque lacinia mi, ut euismod felis mollis id. "
		"Cras pulvinar massa non ultricies ullamcorper. Mauris orci tellus, malesuada sed pellentesque rhoncus, condimentum sed sem. "
		"Praesent nibh felis, sagittis mollis mi id, varius fermentum felis."
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut aliquet est."
		" Sed convallis dignissim justo nec porta. Sed volutpat, purus et efficitur porta, "
		"justo dui ornare eros, eget dictum dui massa nec massa. Nunc finibus gravida euismod. "
		"Praesent quis dui pellentesque, egestas nibh sit amet, fermentum dolor. Donec viverra pretium elementum."
		" Proin fermentum velit a nibh rutrum feugiat. Aliquam vehicula lorem quis justo pretium egestas. "
		"Aliquam erat volutpat. Suspendisse vestibulum tempor dui, ac mollis dolor pellentesque et. "
		"Vestibulum pharetra vel mauris eu egestas. Sed at placerat ligula. In hac habitasse platea dictumst. "
		"Etiam semper sollicitudin velit et hendrerit. Mauris eu pharetra libero.Aliquam vel tortor nec urna semper aliquam. "
		"Etiam at ante blandit, faucibus neque at, eleifend urna. Ut urna odio, tempor non ex nec, tristique volutpat sem. "
		"Quisque libero lorem, pulvinar in faucibus non, vulputate ut elit. Phasellus scelerisque lacinia mi, ut euismod felis mollis id. "
		"Cras pulvinar massa non ultricies ullamcorper. Mauris orci tellus, malesuada sed pellentesque rhoncus, condimentum sed sem. "
		"Praesent nibh felis, sagittis mollis mi id, varius fermentum felis."
		).upper()
absPath = os.path.dirname(os.path.realpath(__file__)) + '/test/img/'
portrait.onUpload('XX14', absPath)
portrait.onRequest('XX14', absPath, value)
portrait.joinLayers('XX14', absPath)