# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20160920_1635'),
        ('booth', '0003_auto_20160919_1931'),
    ]

    operations = [
    ]
