# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_merge_20160921_2101'),
        ('booth', '0004_merge_20160923_1125'),
    ]

    operations = [
    ]
